import "./globals.css";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} grid min-h-screen`}
        style={{ gridTemplateRows: "auto 1fr auto" }}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
